[book]
title = "Speedboat Docs"
authors = ["DeJayDev", "b1naryth1ef", "Wolfiri"]
description = "Documentation for Speedboat, with all this power comes all this configuration."
language = "en"

[output.html]
preferred-default-theme = "ayu"
cname = "https://docs.speedboat.rocks"
git-repository-url = "https://github.com/DeJayDev/speedboat-docs"
edit-url-template = "https://github.com/DeJayDev/speedboat-docs/edit/main/{path}"

[output.html.print]
enable = false
